spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_booking_dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.booking.platform: DEBUG